name: Zero In Pro Home Inspection
favicon: null
layout_spectrum: 0.19547
typography_spectrum: 0.41918
navigation:
  - name: About
    id: f4fdb7df-f8fe-4181-bf7c-7ed767c84b64
    type: content
title: Professional Home Inspection
description: Tagline
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e3e9f5'
    - '#d5954e'
    - '#765b3e'
    - '#6e351c'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
