name: Zero In Home Inspections
favicon: null
layout_spectrum: 0.24497009511105716
typography_spectrum: 0.9681786366272718
title: Zero In Home Inspections
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.17548834695480764
  lightness: 0.09998630941845477
  saturation: 0.6080979534890503
  rhythmicContrast: 0.9490145770832896
purpose: []
