name: Zero In Pro Home Inspection
favicon: null
layout_spectrum: 0.17938
typography_spectrum: 0.25268
navigation:
  - name: About
    id: f4fdb7df-f8fe-4181-bf7c-7ed767c84b64
    type: content
title: Professional Home Inspection
description: Tagline
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7b6558'
    - '#ede4db'
    - '#c0b0a9'
    - '#8d971c'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
